# Generated by Django 2.1 on 2019-01-29 12:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.TextField(choices=[('vehicle', 'vehicle'), ('laptops', 'laptops'), ('mobile', 'mobile'), ('electronics', 'electronics'), ('computer', 'computer'), ('real estate', 'real estate'), ('home appliances', 'home appliances'), ('jobs', 'jobs')], default='else'),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.TextField(choices=[('Egypt', 'Egypt'), ('USA', 'USA'), ('UAE', 'UAE')], default='else'),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to='product_img'),
        ),
        migrations.AddField(
            model_name='products',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
