# Generated by Django 2.1 on 2019-01-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
    ]
