# Generated by Django 2.1.7 on 2019-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20190129_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, default='/product_img/default.bmp', upload_to='product_img'),
        ),
    ]
