# Generated by Django 2.1.7 on 2019-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
