# Generated by Django 2.1.7 on 2019-03-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_products_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='likes',
        ),
    ]
