# Generated by Django 2.1.7 on 2019-03-24 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='to',
            field=models.TextField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
